// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by hack/docgen tool. DO NOT EDIT.

package hv

import (
	"github.com/siderolabs/talos/pkg/machinery/config/encoder"
)

func (ContentLibraryConfigV1Alpha1) Doc() *encoder.Doc {
	doc := &encoder.Doc{
		Type:        "ContentLibraryConfig",
		Comments:    [3]string{"" /* encoder.HeadComment */, "ContentLibraryConfig is a content library configuration document." /* encoder.LineComment */, "" /* encoder.FootComment */},
		Description: "ContentLibraryConfig is a content library configuration document.\nContentLibraryConfig declares a content library: a store for virtual machine images\nkept on a volume.\n\nThe library is a directory named after the document, created under\n`content-library/` on the backing volume, so a library `my-vm-images-1` backed by the\nuser volume `u-vm-images` lives in `/var/mnt/vm-images/content-library/my-vm-images-1`.\nSeveral libraries may share a volume.\n\nContents are managed over the API with `talosctl hv content-library`, never by editing\nthe machine configuration. Status is reported via `ContentLibraryStatus`.\n",
		Fields: []encoder.Doc{
			{
				Type:   "Meta",
				Inline: true,
			},
			{
				Name:        "name",
				Type:        "string",
				Note:        "",
				Description: "Name of the content library.\n\nMust be between 1 and 63 characters long, and can only contain ASCII letters,\ndigits and hyphens. It names the library's directory on the backing volume, and\nis the ID used to address the library over the API.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "Name of the content library." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
			{
				Name:        "backing",
				Type:        "ContentLibraryBacking",
				Note:        "",
				Description: "Volume backing the content library.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "Volume backing the content library." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
		},
	}

	doc.AddExample("", exampleContentLibraryConfigV1Alpha1())

	return doc
}

func (ContentLibraryBacking) Doc() *encoder.Doc {
	doc := &encoder.Doc{
		Type:        "ContentLibraryBacking",
		Comments:    [3]string{"" /* encoder.HeadComment */, "ContentLibraryBacking describes the storage backing a content library." /* encoder.LineComment */, "" /* encoder.FootComment */},
		Description: "ContentLibraryBacking describes the storage backing a content library.",
		AppearsIn: []encoder.Appearance{
			{
				TypeName:  "ContentLibraryConfigV1Alpha1",
				FieldName: "backing",
			},
		},
		Fields: []encoder.Doc{
			{
				Name:        "volume",
				Type:        "string",
				Note:        "",
				Description: "ID of the volume storing the library's contents.\n\nThe volume must be declared separately, and must be a non-system volume with a\nfilesystem: a user volume (`u-` prefix), an existing volume (`e-` prefix) or an\nexternal volume (`x-` prefix). The volume is not provisioned by this document,\nand the library becomes ready only once the volume is mounted.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "ID of the volume storing the library's contents." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
		},
	}

	doc.Fields[0].AddExample("", "u-vm-images")

	return doc
}

// GetFileDoc returns documentation for the file hv_doc.go.
func GetFileDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "hv",
		Description: "Package hv provides hypervisor configuration documents.\n",
		Structs: []*encoder.Doc{
			ContentLibraryConfigV1Alpha1{}.Doc(),
			ContentLibraryBacking{}.Doc(),
		},
	}
}
